[service]
addr = ":9988"
level = "debug"
[log]
path = "./log"
level = "error"
[mysql]
user = "root"
password = "123456"
host = "127.0.0.1"
port = "3306"
db = "adm"
maxIdleConns = 5
maxOpenConns = 20
connMaxLifetime = "600s"
[redis]
addr = "127.0.0.1:6379"
maxIdle = 5
maxActive = 2
idleTimeout = "600s"
readTimeout = "1s"
writeTimeout = "1s"
connectTimeout = "60s"